apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: anychat-chat_service
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: anychat-config
        - secretRef:
            name: anychat-secrets
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"